# Generated by Django 4.0.4 on 2022-07-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0002_submission_submission_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='submission_type',
        ),
        migrations.AddField(
            model_name='template',
            name='submission_type',
            field=models.JSONField(default={'submission_types': []}, null=True, verbose_name='Submission type'),
        ),
    ]
