# Generated by Django 4.0.4 on 2022-07-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0003_remove_template_submission_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalflow',
            name='submission_type',
        ),
    ]
