# Generated by Django 4.0.4 on 2022-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0005_approvalflow_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentfile',
            name='include_in_cover_page',
            field=models.BooleanField(default=True, verbose_name='Include in cover page'),
        ),
    ]
