# Generated by Django 4.0.4 on 2022-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0006_attachmentfile_include_in_cover_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='project',
            name='chop',
            field=models.TextField(blank=True, null=True, verbose_name='Chop'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.TextField(blank=True, null=True, verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Primary name'),
        ),
        migrations.AddField(
            model_name='project',
            name='tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tel'),
        ),
        migrations.AddField(
            model_name='project',
            name='transaction_type_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction type name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status'),
        ),
    ]
