# Generated by Django 4.0.4 on 2022-07-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0007_project_address_project_chop_project_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(null=True, verbose_name='Status'),
        ),
    ]
