# Generated by Django 4.0.4 on 2022-07-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0008_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='contractor_logo_1',
        ),
    ]
