# Generated by Django 4.0.4 on 2022-07-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0011_alter_futurereply_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurereply',
            name='date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Date'),
        ),
    ]
