# Generated by Django 4.0.4 on 2022-07-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0013_alter_futurereply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurereply',
            name='date',
        ),
    ]
