# Generated by Django 4.0.4 on 2022-07-07 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0014_remove_futurereply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='futurereply',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
