# Generated by Django 4.0.4 on 2022-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0015_futurereply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurereply',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
    ]
