# Generated by Django 4.0.4 on 2022-07-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0016_alter_futurereply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurereply',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
