# Generated by Django 4.0.4 on 2022-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0017_alter_futurereply_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='purpose',
            field=models.JSONField(blank=True, null=True, verbose_name='Purpose'),
        ),
    ]
