# Generated by Django 4.0.4 on 2022-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0018_project_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutthissubmission',
            name='purpose_of_submission',
            field=models.JSONField(blank=True, editable=False, null=True, verbose_name='Purpose of submission'),
        ),
    ]
