# Generated by Django 4.0.4 on 2022-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0020_aboutthissubmission_purpose_chosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutthissubmission',
            name='purpose_chosen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purpose chosen'),
        ),
    ]
