# Generated by Django 4.0.4 on 2022-07-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0021_alter_aboutthissubmission_purpose_chosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Trade id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('short_form', models.CharField(blank=True, max_length=255, null=True, verbose_name='Short form')),
                ('status', models.IntegerField(null=True, verbose_name='Status')),
            ],
        ),
    ]
