# Generated by Django 4.0.4 on 2022-07-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0022_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='document_srm_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='Document id for submission to SRM'),
        ),
    ]
