# Generated by Django 4.0.4 on 2022-07-17 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0024_alter_signoff_approval_flow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='document_srm_id',
        ),
        migrations.AlterField(
            model_name='submission',
            name='approval_flow',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_flow', to='SMMapp.approvalflow'),
            preserve_default=False,
        ),
    ]
