# Generated by Django 4.0.4 on 2022-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0025_remove_submission_document_srm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='signoff_has_submitter',
            field=models.BooleanField(default=False, verbose_name='Signoff has submitter'),
        ),
    ]
