# Generated by Django 4.0.4 on 2022-07-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0026_alter_submission_signoff_has_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Comment from internal reviewers'),
        ),
    ]
