# Generated by Django 4.0.4 on 2022-07-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0028_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_reviewer', to='SMMapp.project'),
        ),
    ]
