# Generated by Django 4.0.4 on 2022-07-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0029_reviewer_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviewer',
        ),
    ]
