# Generated by Django 4.0.4 on 2022-07-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0030_delete_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewer_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Reviewer id')),
                ('primary_name', models.CharField(max_length=255, verbose_name='Primary name')),
                ('secondary_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secondary name')),
                ('short_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short name')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='reviewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='SMMapp.reviewer'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='target_recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_recipient', to='SMMapp.reviewer'),
        ),
    ]
