# Generated by Django 4.0.4 on 2022-07-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0031_reviewer_project_reviewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ext_rev',
            field=models.CharField(default='0', editable=False, max_length=10, verbose_name='External version'),
        ),
    ]
