# Generated by Django 4.0.4 on 2022-07-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0033_remove_submission_associated_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='parent_document_number',
            field=models.CharField(default=1, editable=False, max_length=50, verbose_name='Parent document number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='sequence_number',
            field=models.IntegerField(default=1, editable=False, verbose_name='Sequence number'),
        ),
    ]
