# Generated by Django 4.0.4 on 2022-07-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0034_submission_parent_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_reference_number_structure',
            field=models.JSONField(default={'structure': []}, verbose_name='Submission ref. no. structure'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='document_number',
            field=models.CharField(editable=False, max_length=50, verbose_name='System Id'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='parent_document_number',
            field=models.CharField(editable=False, max_length=50, verbose_name='Parent System Id'),
        ),
        migrations.AlterField(
            model_name='title',
            name='no_of_submission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Document number'),
        ),
    ]
