# Generated by Django 4.0.4 on 2022-07-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0035_project_submission_reference_number_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_reference_number',
            field=models.CharField(default=1, editable=False, max_length=255, verbose_name='Submission reference number'),
            preserve_default=False,
        ),
    ]
