# Generated by Django 4.0.4 on 2022-08-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMMapp', '0038_purpose_remove_project_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(1, 'In progress'), (2, 'Awaiting approval'), (3, 'Submitted'), (4, 'Rejected')], default=1, editable=False, verbose_name='Status'),
        ),
    ]
